# travis config for KappaTools
sudo: required
language: cpp
services: docker
notifications:
  email:
    on_success: change
    on_failure: always
compiler: gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
before_install:
  - sudo apt-get -y install libboost1.54-all-dev root-system
  - ls /usr/include/root /usr/lib/*/root5.34
  - python --version
  - root-config --cflags --ldflags
  - cd ..
  - git clone --depth=10 https://github.com/KappaAnalysis/Kappa.git
  - make -C Kappa/DataFormats/test
  - cd KappaTools
  - export KAPPAPATH=../Kappa
install:
  - cmake .
  - make VERBOSE=1
script: ls
